### ISSUE TITLE
6.hafta U-net ile segmentasyon hk.

### ISSUE THREAD

**Issue by omersokmaz** [TeknoTAM/Estu-Teknotam-Akademi#1]
Merhaba,U-net ile segmentasyon kısmında ilgili dosyaları hangi sıra ile çalıştırmamız gerekiyor acaba,bir de U-net'in alternatif implementasyonunu da yaptınız sanırsam onlardan hangisini çalıştırmamız gerekiyor? Son olarak da örneğin 600x400 boyutunda bir resmi U-net ile eğitemez miyim kesinlikle 512x mı olmalı?

Teşekkürlerimle.

**Comment by burakalperen** [comment]
Merhaba Ömer, geri bildirimin için sağol. Kodları daha rahat çalıştırmak için repoyu güncelledim, config içerisinden model_type parametresini 2 farklı model için de ayarlayıp eğitim ve prediction kodlarını direk çalıştırabilirsin. 2.sorun için Unet'i farklı width-height değerleri için de eğitebilirsin. Ama encoder ile decoder kısımları arasındaki bağlantıları sağlayabilmen için mimarideki evrişimsel filtrelerin parametre değerlerini ona göre ayarlamasın. Unet mimarisinden dolayı tensor'lerin birçok kez 2'ye bölünmesi gerekiyor. Daha basit bir yöntem olarak katmanlardaki çıktıları 2'ye bölünebilir hale getirmek için padding işlemi uygulayabilirsin.
